// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4UNPcsHUrUxPvFaqkssa-gyBJMhP2FqU',
    appId: '1:614709227604:android:c65156cbf182bd08c7fdc1',
    messagingSenderId: '614709227604',
    projectId: 'rental-room-f8799',
    storageBucket: 'rental-room-f8799.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7LBamvVKwHy2UgBmhLkRlzc45hQsdpUY',
    appId: '1:614709227604:ios:b89d9d5ae2c10dc3c7fdc1',
    messagingSenderId: '614709227604',
    projectId: 'rental-room-f8799',
    storageBucket: 'rental-room-f8799.firebasestorage.app',
    iosBundleId: 'com.example.rentalRoom',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7LBamvVKwHy2UgBmhLkRlzc45hQsdpUY',
    appId: '1:614709227604:ios:b89d9d5ae2c10dc3c7fdc1',
    messagingSenderId: '614709227604',
    projectId: 'rental-room-f8799',
    storageBucket: 'rental-room-f8799.firebasestorage.app',
    iosBundleId: 'com.example.rentalRoom',
  );
}
